"""empty message

Revision ID: 110cbcc87c25
Revises: 375d8f21ecee
Create Date: 2026-03-25 14:38:42.186974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110cbcc87c25'
down_revision = '375d8f21ecee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('follower')
    op.drop_table('following')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('comment_creator_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('creator_id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('post_creator_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_creator_id_fkey', 'user', ['creator_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_creator_id_fkey', 'user', ['creator_id'], ['id'])
        batch_op.drop_column('user_id')

    op.create_table('following',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('following_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['following_id'], ['user.id'], name='following_following_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='following_pkey')
    )
    op.create_table('follower',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name='follower_follower_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='follower_pkey')
    )
    op.drop_table('follows')
    # ### end Alembic commands ###
