"""empty message

Revision ID: 375d8f21ecee
Revises: 3910a8a7246c
Create Date: 2026-03-25 10:46:38.128268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375d8f21ecee'
down_revision = '3910a8a7246c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('following', schema=None) as batch_op:
        batch_op.drop_constraint('following_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('following', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('following_user_id_fkey', 'user', ['user_id'], ['id'])

    op.drop_table('follower')
    # ### end Alembic commands ###
