"""empty message

Revision ID: 3910a8a7246c
Revises: ee75ec7649aa
Create Date: 2026-03-25 10:19:37.306023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3910a8a7246c'
down_revision = 'ee75ec7649aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('following',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['following_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('follower')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('followers_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('following_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['followers_id'], ['user.id'], name='follower_followers_id_fkey'),
    sa.ForeignKeyConstraint(['following_id'], ['user.id'], name='follower_following_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='follower_pkey')
    )
    op.drop_table('following')
    # ### end Alembic commands ###
